---
- name: Set Nginx conf files
  template:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - ../files/nginx.conf/*.j2
  notify: Reload Nginx